### ISSUE TITLE
GUI - segfault during advanced scan

### ISSUE THREAD

**Issue by joncppl** [emericg/SmartServoFramework#18]
System: Ubuntu 16.04 LTS
GUI built with qmake5

using a usb2ax, connected to various configs of dynamixels (ax12, mx28, xl-320)

Typically it will find them right away if the dynamixels are configured with lower baudrates, but if I do an advanced scan (Quick or Full) to find ones with other baudrates, I get this error message and the GUI crashes

```
[I][D-API][DynamixelSimpleAPI] - Using Dynamixel communication protocol version 1
[W][SERIAL][convertBaudRateFlag] convertBaudRateFlag(666666) has been set to B38400 (custom speed will be used)
[I][SERIAL][SerialPortLinux] - Device name has been set to: 'ttyACM0'
[I][SERIAL][SerialPortLinux] - Device node has been set to: '/dev/ttyACM0'
[I][SERIAL][SerialPortLinux] - Device baud rate has been set to: '666666'
Segmentation fault (core dumped)
```

**Comment by emericg** [comment]
Hi,
I pushed a fix on master that might be related to your bug, can you give it a try? Thanks!

**Comment by joncppl** [comment]
Doesn't appear to crash with the new code.
Thanks!
