### ISSUE TITLE
serialport Error: [Running SmartServoGui on Debian]

### ISSUE THREAD

**Issue by Ashok12698** [emericg/SmartServoFramework#31]
Hi, Thanks for sharing this great application.
I am following this as mentioned in the document. while running /SmartServoFramework/SmartServoGui, I am facing an error.

applying command: qmake

**_Project MESSAGE: Using GCC compiler
Project MESSAGE: Building on Linux/BSD plateform
Project ERROR: Unknown module(s) in QT: serialport_**

Please help!

**Comment by emericg** [comment]
Hi,
You're probably just missing the libqt5serialport5 package, try to install it and let me know.
